### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by BaileyJM02** [jexia/maestro#31]
Hello, just a small one. The "[🚀 Examples](https://github.com/jexia/maestro/tree/master/examples)" links send the user to a non-existent directory `/examples`.

### Fix Proposals
1. Update all links to `github.com/jexia/maestro/tree/master/example` from `github.com/jexia/maestro/tree/master/examples`; or,
2. Rename the `/example` directory to `/examples`. *This would have better grammer and fix all URL issues.*

**Comment by jeroenrinzema** [comment]
👋 @BaileyJM02, thank you for showing interest in Maestro. I could pick up this issue or feel free to create a PR to rename the `/example` directory to `/examples`.

**Comment by jeroenrinzema** [comment]
Tyvm for the PR! Feel free to open a new issue when you have a bug or feature request 😃 .
